# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72fa8e676c89c2d77b59576bef918cfa95e89621352cbc65bb76e642c25cbb6f6828753b1dc84206d13dfbe122b2a3dbb8fcd28ac83f4e878ea84e0780753ded

test:
  secret_key_base: f3a6e46cfb3af824fc40a39000c894b5afe26725ff666b2e533c669512e57b9a0d0a184285fa1fa2304fdb8dada0bb6660277c72fac4bd3161c9d4d09c8ed7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
